# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246b838d7bee9ee55e829a32be73ec24f7d97252a53cbe967b6b2830fc12e58d376f2dde926a5036f9f8b4d6bb799e9adf32b22d397e7c8fd9a0ed08cfaab4be

test:
  secret_key_base: 82369de1939233f8d5ae374eed295d3e7baca704c42fbeecaa1bdc6d59883e70607c0fc497ea600803d99a056aa5f05cdde800d9510efd8e34285255a1b72f4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
